### ISSUE TITLE
Cannot install grate with dotnet run and .NET 9

### ISSUE THREAD

**Issue by johan-byggtjanst** [grate-devs/grate#714]
**Describe the bug**
Trying Grate with a .NET 9 project and the installation fails.

**To Reproduce**
Create a console app with .NET 9
Run the following commands.

    dotnet new tool-manifest
    dotnet tool install --local grate --version 2.0.5

**Expected behavior**
Grate should be installed as a dotnet command.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11

**Additional context**
Got the error 
> Unhandled exception: Command 'grate' uses unsupported runner ''."

**Comment by JaDuyve** [comment]
Installing dotnet sdk / runtime  10 on my machine fixed the issue for me.
Question: when grate is build as a selfcontained executable is the runtime on the machine still needed?

**Comment by wokket** [comment]
No, self-contained shouldn't need the runtime.  It's possible we need to use a self-contained in the tool package, trading runtime flexibility for tool download size/time in pipelines.  We could also look at whether we can include multiple copies of the tool, one for each supported runtime, but I'm definitely at the edge of my knowledge there.

**Comment by JaDuyve** [comment]
This maybe an interesting article regarding this issue.

https://andrewlock.net/using-and-authoring-dotnet-tools/

**Comment by jotterbein-sltx** [comment]
This is a problem with .NET 8 also

<img width="1893" height="1205" alt="Image" src="https://github.com/user-attachments/assets/8403e11e-ec4a-4db4-b24c-499fdb1f5e2a" />



To reproduce:

dotnet-tools.json
```
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "grate": {
      "version": "2.0.5",
      "commands": [
        "grate"
      ],
      "rollForward": false
    }
  }
}
```

global.json
```
{
  "sdk": {
    "version": "8.0.0",
    "rollForward": "latestFeature",
    "allowPrerelease": false
  }
}
```

**Comment by wokket** [comment]
I'm away from the computer for a bit and don't know much about the dotnet-tool tooling. If anyone is willing to throw a PR in it would be appreciated

**Comment by hoangthanh28** [comment]
Can you guys try with `grate` 2.0.6? It should be fixed

Thanks.

**Comment by jotterbein-sltx** [comment]
I still can't install 2.0.6 using .NET 8:

08:53:32 D:\dev\grate-test> dir

    Directory: D:\dev\grate-test

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2026-06-24  8:49 AM                .config
-a---          2026-06-24  8:53 AM             86 global.json

08:53:42 D:\dev\grate-test> cat ./.config/dotnet-tools.json
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "grate": {
      "version": "1.7.4",
      "commands": [
        "grate"
      ],
      "rollForward": false
    }
  }
}
08:53:46 D:\dev\grate-test> cat ./global.json
{
  "sdk": {
    "version": "8.0.204",
    "rollForward": "latestFeature"
  }
}
08:53:48 D:\dev\grate-test> dotnet tool install grate --version 2.0.6
Unhandled exception: Microsoft.DotNet.ToolPackage.ToolConfigurationException: Format version is higher than supported. This tool may not be supported in this SDK version. Update your SDK.
   at Microsoft.DotNet.ToolPackage.ToolConfigurationDeserializer.Deserialize(String pathToXml)
   at Microsoft.DotNet.ToolPackage.ToolPackageInstance.DeserializeToolConfiguration(LockFileTargetLibrary library)
   at Microsoft.DotNet.ToolPackage.ToolPackageInstance.GetToolConfiguration()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.DotNet.ToolPackage.ToolPackageInstance.GetCommands()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallLocalCommand.InstallToolUpdate(ToolManifestPackage existingPackage, IToolPackage toolDownloadedPackage, FilePath manifestFile, PackageId packageId)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallLocalCommand.ExecuteInstallCommand(PackageId packageId)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallLocalCommand.Execute()
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)



It installs if I target .NET 10, but for now I can't do that

**Comment by wokket** [comment]
@jotterbein-sltx I've published grate 2.1.2 which now includes a single self-contained grate executable instead of 3 framework-dependent images, one each for 8/9/10:

<img width="925" height="481" alt="Image" src="https://github.com/user-attachments/assets/8e4b0207-617f-4b13-b957-38a325275c89" />

Could you please retest and let me know if this is sorted for you?

**Comment by jotterbein-sltx** [comment]
I don't see any difference on my end:

<img width="1904" height="674" alt="Image" src="https://github.com/user-attachments/assets/db0ef306-c16d-4e56-885c-f109cb8b149c" />


To recreate make a new directory/project, global.json:
```
{
  "sdk": {
    "version": "8.0.204",
    "rollForward": "latestFeature"
  }
}
``` 

Then new manifest and install:
```
dotnet new tool-manifest
dotnet tool install grate --version 2.1.2
```

It works fine with no pinned .NET, or using .NET 10 explicitly.

**Comment by wokket** [comment]
I've been able to repro this by locking an app to net9 (I haven't had the net8 sdk installed for yonks), so that's... good.. I guess.

I have no idea why this is an issue though, self-contained doesn't need the higher runtime:

<img width="1225" height="376" alt="Image" src="https://github.com/user-attachments/assets/711d515f-e76c-46ca-80e9-0428030178ce" />

EDIT:
I've burnt 3 hrs on this now and am out of playtime.  I _think_ the issue is [RID publishing](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/10.0/dotnet-tool-pack-publish) introduced in net10.  

Unfortunately a combination of factors means I can't test the fix locally (the `--source` arg to look for tools locally isn't avail in net8, it keeps using cached nuget packages instead of pulling fresh, --add-source doesn't have the same semantics as --source,, who knows what else)... I've reached a point where I'm generating the tool packages locally using grate net10 sdk and an up to date `main` branch, and my test console app locked to net8 installs them fine... Maybe the tool package version check is on the server side of nuget?  Maybe it's finding cached valid packages somewhere, dunno....


<img width="1477" height="931" alt="Image" src="https://github.com/user-attachments/assets/0c60fc84-672b-43aa-9537-f277e853244c" />

**Comment by wokket** [comment]
I've published 2.1.3 as a pre-release that disables RID publishing under net 10, and works one-in-a-row for me locally:

<img width="1466" height="556" alt="Image" src="https://github.com/user-attachments/assets/e167a0c4-5445-4ffa-b3fa-5fb9ee5b6d8b" />

If someone else can confirm that would be great.

**Comment by jotterbein-sltx** [comment]
2.1.3 worked for me when pinning to .NET 8!

**Comment by hoangthanh28** [comment]
Closing this issue, feel free to reopen if we need more discussions.

Thanks.
